# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Reaz Elias
description: "
I’m Reaz Elias - a Data Scientist with a passion for solving real-world problems using data.
With a PhD in Industrial Engineering, over three years of startup experience, and recent certifications in machine learning and cloud (AWS), I bring a unique blend of research, industry, and teaching experience.
My technical toolkit includes Python, SQL, Scikit-learn, XGBoost, and cloud tools like S3 and SageMaker. I'm especially drawn to projects that involve customer insights, NLP, or deploying ML models at scale.
Currently open to full-time roles where I can contribute meaningfully — whether through predictive modeling, analytics, or building production-grade ML pipelines.
"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Toronto, Canada"
resume_url: /docs/Resume-EliasReaz.pdf
avatar_image: /img/old_photo_1.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/reaz-ussalamelias/" # Add your linkedln handle
github: "https://github.com/EliasReaz/"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

